/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import processing.core.PApplet;

class AppTest {

    //Testing the construction of an App class
    @Test 
    public void appConstructorTest() throws InterruptedException {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
        Thread.sleep(1000);
    }

    //Testing the main methods belonging to App
    @Test
    public void mainAppTest() throws InterruptedException {
        App appTest = new App() {
            public void exit() {
                this.dispose();
            }
        };
        PApplet.runSketch(new String[]{"App"}, appTest);    
        appTest.setup();
        appTest.settings();
        appTest.keyPressed();

        assertFalse(App.manager.gameOver());
        assertTrue(App.manager.loadImages());
        assertFalse(App.manager.winCheck());
        appTest.exit();
        Thread.sleep(1000);
    }
}

