/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class EntityTest {

    //Testing the construction of an Entity
    @Test 
    public void tickTest() throws InterruptedException {
        Entities eTest = new Walls(0,0,false,null);
        eTest.tick();
        Thread.sleep(1000);
    }

    //Testing the construction and functionality of Fruit and SuperFruit
    @Test
    public void FruitTest() throws InterruptedException {
        Fruit.resetEaten();
        Collectibles sfTest = new SuperFruit(0,0,false,null);
        sfTest.tick();
        assertTrue(SuperFruit.isActive());
        sfTest.tick();

        Entities fruitTest = new Fruit(0,0,false,null);
        fruitTest.tick();
        assertTrue(Fruit.eaten == 1);
        Fruit.resetEaten();
        assertTrue(Fruit.eaten == 0);
        Thread.sleep(1000);
    }

    //Testing the functionality of Soda
    @Test
    public void SodaTest() throws InterruptedException {
        Soda.setActive(false);
        Collectibles sodaTest = new Soda(0,0,false,null);
        sodaTest.tick();
        assertTrue(Soda.isActive());
        sodaTest.tick();
        Thread.sleep(1000);
    }
}
